name: Daily arXiv Paper Fetch and Filter

on:
  schedule:
    # Runs 'at 01:00 UTC' every day
    - cron: '0 1 * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to commit changes back to the repo

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Use the latest available 3.x version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run script to fetch, filter, and generate report
      env:
        OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      run: python src/main.py

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add daily_json/
        git add daily_html/
        # Optionally add index.html if it's modified by the script
        # git add index.html
        # Check if there are changes to commit
        if ! git diff --staged --quiet; then
          git commit -m "Automated daily arXiv report update"
          git push
        else
          echo "No changes to commit."
        fi